export const LOGGING_USER = "LOGGING_USER";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const REGISTERING_USER = "REGISTERING_USER";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";

export const UPDATING_USER = "UPDATING_USER";
export const USER_UPDATED = "USER_UPDATED";
export const USER_UPDATION_FAILED = "USER_UPDATION_FAILED";

export const LOGGING_OUT_USER = "LOGGING_OUT_USER";
export const LOGGED_OUT_SUCESSFULLY = "LOGGED_OUT_SUCESSFULLY";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

export const LOGGING_OUT_OF_ALL_DEVICES = "LOGGING_OUT_OF_ALL_DEVICES";
export const LOGGED_OUT_OF_ALL_DEVICES = "LOGGED_OUT_OF_ALL_DEVICES";
export const LOGOUT_FROM_ALL_FAILED = "LOGOUT_FROM_ALL_FAILED";

export const DELETING_USER = "DELETING_USER";
export const USER_DELETED = "USER_DELETED";
export const USER_DELETION_FAILED = "USER_DELETION_FAILED";

export const FETCHING_USER_LOCATION = "FETCHING_USER_LOCATION";
export const FETCHING_LOCATION_FAILED = "FETCHING_LOCATION_FAILED";
export const LOCATION_FETCHED_SUCESSFULLY = "LOCATION_FETCHED_SUCESSFULLY";

export const FINDING_ALL_DONORS = "FINDING_ALL_DONORS";
export const ALL_DONORS_FOUND = "ALL_DONORS_FOUND";
export const FINDING_DONORS_FAILED = "FINDING_DONORS_FAILED";

export const REGISTERING_AS_DONOR = "REGISTERING_AS_DONOR";
export const REGISTERED_AS_DONOR = "REGISTERED_AS_DONOR";
export const FAILED_TO_REGISTER_AS_DONOR = "FAILED_TO_REGISTER_AS_DONOR";

export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
